
BasicErrors -> BuySubmit: callback

BuySubmit -> Portfolio: buyStock(ticker, dollars)
Portfolio -> Portfolio: Buying model operations

alt Success
	Portfolio --> BuySubmit: (buyStock)
	BuySubmit --> BasicErrors: (callback)
else Not enough cash
	Portfolio --> BuySubmit: NotEnoughCash
	BuySubmit --> BasicErrors: (callback) BadInput("You don't have enough cash")
else Negative volume
	Portfolio --> BuySubmit: NegativeVolume
	BuySubmit --> BasicErrors: (callback) BadInput("You must buy more than $0.00")
end

