
participant "A view component" as View

View -> Portfolio: buyStock(ticker, shares)

alt Portfolio.cash < dollars
	Portfolio --> View: (buyStock) NotEnoughCash
else shares < 0
	Portfolio --> View: (buyStock) NegativeVolume
else Success
	Portfolio --> View: (buyStock)
end

