
Jetty -> LiftServlet: doPost
LiftServlet -> LiftRules: dispatch

LiftRules -> Field1: onSubmit
LiftRules -> Field2: onSubmit
LiftRules -> ...: onSubmit

LiftRules -> Submit: onSubmit

Submit -> Submit: [Processing and Error Handling]

Submit --> LiftRules: (onSubmit)
LiftRules --> LiftServlet: (dispatch)
LiftServlet --> Jetty: (doPost)

