
participant Submit
participant Form
participant Field1
participant Field2
participant ...

Submit -> Form: process

Form -> Field1: process
Field1 --> Form: (process)
Form -> Field2: process
Field2 --> Form: (process)
Form -> ...: process
... --> Form: (process)

alt Success
Form --> Submit: (process) Some(result)
else Bad inputs
Form --> Submit: (process) Nothing
end

