
BasicErrors -> SellSubmit: callback

SellSubmit -> Portfolio: sellAll(ticker)
Portfolio -> Portfolio: Selling model operations

alt Success
	Portfolio --> SellSubmit: (sellAll)
	SellSubmit --> BasicErrors: (callback)
else Don't own this stock
	Portfolio --> SellSubmit: (sellAll) DontOwnStock
	SellSubmit --> BasicErrors: (callback) BadInput("You don't own this stock")
end

