
participant "Portfolio (buyer)" as Buyer
participant "Portfolio (seller)" as Seller
participant "Portfolio (voter)" as Voter

View -> Voter: userVoteUp(ev: NewsEvent, aside: DerivativeBuyerSetAside)
Voter -> Voter: enterContract
Voter -> Buyer: enterContract
Voter -> DerivativeSellerVote: insert()

